services:
  weather_cli:
    container_name: weather_cli
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/weather_cli
    command: bash -c 'composer install && chmod +x weather && php -a'
    tty: true
    stdin_open: true